sonic:
  agent:
    host: 192.168.0.2
    port: 7777
    key: 29002272-4659-4808-a804-08ce3388b136
  server:
    host: 192.168.0.2
    folder-port: 8094
    transport-port: 8095

modules:
  android:
    enable: true
  ios:
    enable: true
    wda-bundle-id: com.sonic.wda
    wda-ipa-name: sonic-wda.ipa
  webview:
    enable: true
    chrome-driver-path: C:\Program Files\Google\Chrome\Application\chromedriver.exe

logging:
  file:
    name: logs/sonic-agent.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3
