sonic:
  agent:
    host: 127.0.0.1
    port: 7777
    key: 7bbc50da-1c7b-43e7-9d5d-4e8a86fa896a
  server:
    host: 127.0.0.1
    folder-port: 8094
    transport-port: 8095

modules:
  android:
    enable: true
    use-adbkit: false
  ios:
    enable: false
    wda-bundle-id: com.sonic.wda.xctrunner
  appium:
    enable: true
  webview:
    enable: true
    chrome-driver-debug-port: 7778
    chrome-driver-path: "/Applications/Google Chrome.app/Contents/MacOS/chromedriver"

logging:
  file:
    name: logs/sonic-agent.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3
