server:
  port: 7777

spring:
  application:
    name: apex-agent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: sonic
    listener:
      simple:
        acknowledge-mode: manual
      retry:
        enabled: true
        max-attempts: 5
        max-interval: 60000
        initial-interval: 60000
    publisher-confirm-type: correlated
    publisher-returns: true

sonic:
  folder:
    url: http://localhost:8094/api/folder
