server:
  port: 7777

spring:
  application:
    name: apex-agent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: sonic
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true

sonic:
  folder:
    url: http://localhost:8094/api/folder
  agent:
    key: 1
